apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: tjit
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tjit
    app.kubernetes.io/part-of: byoc-app-gzks
  name: tjit
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: tjit
status:
  loadBalancer: {}
